pdp/tutorial/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from pdp.tutorial import views
from pdp.tutorial import feeds

urlpatterns = patterns(
    '',

    url(r'^flux/rss/$', feeds.LastTutorialsFeedRSS(),
        name='tutorial-feed-rss'),
    url(r'^flux/atom/$', feeds.LastTutorialsFeedATOM(),
        name='tutorial-feed-atom'),

    # Viewing

    # Current URLs
    url(r'^auteur/(?P<name>.+)$', views.by_author),
    url(r'^categorie/(?P<name>.+)$', views.by_category),
    url(r'^tag/(?P<name>.+)$', views.by_tag),
    url(r'^tags/$', views.tags),

    url(r'^(?P<tutorial_pk>\d+)/(?P<tutorial_slug>.+)/'
        r'(?P<part_slug>.+)/'
        r'(?P<chapter_slug>.+)/$',
        views.view_chapter, name="view-chapter-url"),

    url(r'^(?P<tutorial_pk>\d+)/(?P<tutorial_slug>.+)/'
        r'(?P<part_slug>.+)/$', views.view_part, name="view-part-url"),

    url(r'^(?P<tutorial_pk>\d+)/(?P<tutorial_slug>.+)/$',
        views.view_tutorial, name="view-tutorial-url"),

    url(r'^telecharger$', views.download),

    # Editing

    url(r'^editer/tutoriel$', views.edit_tutorial),
    url(r'^modifier/tutoriel$', views.modify_tutorial),
    url(r'^modifier/partie$', views.modify_part),
    url(r'^editer/partie$', views.edit_part),
    url(r'^modifier/chapitre$', views.modify_chapter),
    url(r'^editer/chapitre$', views.edit_chapter),
    url(r'^modifier/extrait$', views.modify_extract),
    url(r'^editer/extrait$', views.edit_extract),

    # Adding

    url(r'^nouveau/tutoriel$', views.add_tutorial),
    url(r'^nouveau/tutoriel/import$', views.import_tutorial),
    url(r'^nouveau/partie$', views.add_part),
    url(r'^nouveau/chapitre$', views.add_chapter),
    url(r'^nouveau/extrait$', views.add_extract),

    url(r'^$', views.index),
)

pdp/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from django.contrib import admin
admin.autodiscover()

import pdp.pages.views
import pdp.settings

urlpatterns = patterns(
    '',

    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),

    url(r'^$', pdp.pages.views.home),

    url(r'^recherche/', SearchView(
        template='search/search.html',
        form_class=ModelSearchForm),
        name='haystack_search'),

    url(r'^robots\.txt$', pdp.pages.views.robots),

) + static(pdp.settings.MEDIA_URL, document_root=pdp.settings.MEDIA_ROOT)

# Serve debug toolbar files on debug
if pdp.settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)))

# Make Django serve the files if needed (local versions)
if pdp.settings.SERVE:
    urlpatterns += patterns(
        '',

        # Static content for website assets
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.STATIC_ROOT}),

        # User-uploaded content
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.MEDIA_ROOT}),
    )

pdp/tutorial/models.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

"""Models for tutorial app.

The class hierarchy is as follows :

 - Large tutorials: Tutorial < Parts < Chapters < Extracts
 - Medium tutorials: Tutorial < Part < Chapters < Extracts
 - Small tutorials : Tutorial < Chapter < Extracts

Each class may provide some hierarchy fields or methods in order to access its
parent (or children) object(s).

"""

import os
import datetime
import io

from django.db import models
from django.db.models.signals import post_save

from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse
from django.core.files.uploadedfile import SimpleUploadedFile

from taggit.managers import TaggableManager

from PIL import Image

from pdp.tutorial.exceptions import \
    OrphanPartException, OrphanChapterException

from pdp.utils import slugify
from pdp.utils.models import has_changed

IMAGE_MAX_WIDTH = 64
IMAGE_MAX_HEIGHT = 64


def image_path(instance, filename):
    """Get path to a tutorial image.

    Returns:
        string

    """
    ext = filename.split('.')[-1]
    filename = u'original.{}'.format(ext.lower())
    return os.path.join('tutorials', str(instance.pk), filename)


def thumbnail_path(instance, filename):
    """Get path to a tutorial thumbnail.

    Returns:
        string

    """
    ext = filename.split('.')[-1]
    filename = u'thumb.{}'.format(ext.lower())
    return os.path.join('tutorials', str(instance.pk), filename)


class TutorialCategory(models.Model):

    """A way to organize tutorials in different categories."""

    class Meta:
        verbose_name = u'Catégorie de tutoriel'
        verbose_name_plural = u'Catégories de tutoriel'

    title = models.CharField(
        u'Titre',
        max_length=80
    )

    slug = models.SlugField(max_length=80)

    def __str__(self):
        """Textual representation of a category."""
        return self.title

    def get_absolute_url(self):
        """Get URL to view the category.

        Returns:
            string

        """
        return reverse('pdp.tutorial.views.by_category', args=(
            self.slug,
        ))

    def get_tutorial_count(self):
        """Return number of visible tutorials in this category.

        Returns:
            int

        """
        return Tutorial.objects \
            .filter(is_visible=True) \
            .filter(category__pk=self.pk) \
            .count()


class Tutorial(models.Model):

    """A tutorial.

    Can even ben small, medium or big (check the `size` field).

    """

    class Meta:
        verbose_name = u'Tutoriel'
        verbose_name_plural = u'Tutoriels'

    SMALL = 'S'
    MEDIUM = 'M'
    BIG = 'B'

    SIZE_CHOICES = (
        (SMALL, u'Mini'),
        (MEDIUM, u'Standard'),
        (BIG, u'Étendu'),
    )

    title = models.CharField(
        u'Titre',
        max_length=80
    )

    description = models.CharField(
        u'Description',
        max_length=200
    )

    authors = models.ManyToManyField(
        User,
        verbose_name=u'Auteurs'
    )

    image = models.ImageField(
        upload_to=image_path,
        blank=True, null=True,
        default=None
    )

    thumbnail = models.ImageField(
        upload_to=thumbnail_path,
        blank=True, null=True,
        default=None
    )

    introduction = models.TextField(
        u'Introduction',
        null=True, blank=True
    )

    conclusion = models.TextField(
        u'Conclusion',
        null=True, blank=True
    )

    slug = models.SlugField(max_length=80)

    pubdate = models.DateTimeField(
        u'Date de publication',
        blank=True
    )

    update = models.DateTimeField(
        u'Date d’édition',
        null=True, blank=True
    )

    # We could distinguish large/small tutorials by looking at what chapters
    # are contained directly in a tutorial, but that'd be more complicated
    # than a field.
    size = models.CharField(
        u'Taille du tutoriel',
        max_length=1,
        choices=SIZE_CHOICES,
        default=BIG
    )

    is_visible = models.BooleanField(
        u'Est visible publiquement',
        default=False
    )

    is_pending = models.BooleanField(
        u'Est en attente',
        default=False
    )

    is_beta = models.BooleanField(
        u'Est en bêta',
        default=False
    )

    category = models.ForeignKey(
        TutorialCategory,
        null=True, blank=True,
        verbose_name=u'Catégorie'
    )

    tags = TaggableManager()

    is_article = models.BooleanField(
        u'Est un article',
        default=False
    )

    def __str__(self):
        """Textual representation of a tutorial.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view this tutorial.

        Returns:
            string

        """
        return reverse('pdp.tutorial.views.view_tutorial', args=[
            self.pk, slugify(self.title)
        ])

    def get_pdf_url(self):
        """Get URL of the generated PDF file from this tutorial.

        Returns:
            string

        """
        return u'{}/tutorials/{}/{}.pdf'.format(
            settings.MEDIA_URL,
            self.pk,
            self.slug,
        )

    def get_md_url(self):
        """Get URL of the generated Markdown file from this tutorial.

        Returns:
            string

        """
        return u'{}/tutorials/{}/{}.md'.format(
            settings.MEDIA_URL,
            self.pk,
            self.slug,
        )

    def has_pdf(self):
        """Check if the tutorial has a PDF file.

        Returns:
            boolean

        """
        return os.path.isfile(os.path.join(
            settings.MEDIA_ROOT,
            'tutorials',
            str(self.pk),
            u'{}.pdf'.format(self.slug),
        ))

    def has_md(self):
        """Check if the tutorial has a Markdown file.

        Returns:
            boolean

        """
        return os.path.isfile(os.path.join(
            settings.MEDIA_ROOT,
            'tutorials',
            str(self.pk),
            u'{}.md'.format(self.slug),
        ))

    def get_edit_url(self):
        """Get URL to edit this tutorial.

        Returns:
            string

        """
        return u'/tutoriel/editer?tutoriel={0}'.format(self.pk)

    def get_parts(self):
        """Get the parts associated with the tutorial if it's big.

        Returns:
            QuerySet on Part objects

        """
        return Part.objects.all()\
            .filter(tutorial__pk=self.pk)\
            .order_by('position_in_tutorial')

    def get_part(self):
        """Get the part associated with the tutorial if medium.

        Returns:
            Part object or None

        """
        return self.get_parts().first()

    def get_chapter(self):
        """Get the chapter associated with the tutorial if it's small.

        Returns:
            Chapter or None

        Raises:
            CorruptedTutorialError

        """
        if not self.size == Tutorial.SMALL:
            return None

        try:
            # We can use get since we know there'll only be one chapter
            return Chapter.objects.get(tutorial__pk=self.pk)
        except Chapter.DoesNotExist:
            # Whoops, this tutorial is broken!
            return None

    def save(self, *args, **kwargs):
        """Save tutorial instance.

        If tutorial's image was changed, it will update its thumbnail field
        resizing it. Then it will call normal saving of the model.

        """

        is_new = self.pk is None
        thumb_size = (IMAGE_MAX_HEIGHT, IMAGE_MAX_WIDTH)

        # Save the tutorial first if it was created in order to have a pk from
        # the database.
        if is_new:
            super().save(*args, **kwargs)

        # Compute tutorial's slug from its title
        self.slug = slugify(self.title)

        # Update the thumbnail if necessary
        if self.image and (is_new or has_changed(self, 'image')):
            # TODO : delete old image

            image = Image.open(self.image)

            if image.mode not in ('L', 'RGB'):
                image = image.convert('RGB')

            image.thumbnail(thumb_size, Image.ANTIALIAS)

            # Save the thumbnail to memory
            temp_handle = io.BytesIO()
            image.save(temp_handle, 'png')
            temp_handle.seek(0)  # rewind the file

            # Save to the thumbnail field
            suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
                                     temp_handle.read(),
                                     content_type='image/png')
            self.thumbnail.save(u'{}.png'.format(suf.name), suf, save=False)

        # Save the tutorial
        super().save(*args, **kwargs)


def get_last_tutorials():
    """Get the last published tutorials.

    This should be used for the home page tutorial displaying.

    Returns:
        list of Tutorial

    """
    return Tutorial.objects.all() \
        .filter(is_visible=True) \
        .order_by('-pubdate')[:5]


class Part(models.Model):

    """A part, containing chapters."""

    class Meta:
        verbose_name = u'Partie'
        verbose_name_plural = u'Parties'

templates/tutorial/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Tutoriels
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.tutorial.views.index" %}">Tutoriels</a></li>
{% endblock %}

{% block menu_tutorial %}
    class="active"
{% endblock %}

templates/tutorial/by_author.html
{% extends "tutorial/base.html" %}
{% load humanize %}
{% load profile %}
{% load emarkdown %}

{% block title %}
    Tutoriels rédigés par {{ usr.username }}
{% endblock %}

{% block headline %}
    Tutoriels rédigés par {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
    <li class="unavailable"><a href="#">Par auteur</a></li>
    <li class="current"><a href="#">{{ usr.username }}</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <table>
          <thead>
            <tr>
              <th width="15%">Tutoriels</th>
              <th width="10%">Quand</th>
              <th width="30%">Introduction</th>
            </tr>
          </thead>
          <tbody>
            {% for tutorial in tutorials %}
            <tr>
                <td>
                    <div>
                        {% if tutorial.thumbnail %}
                            <img src="{{ tutorial.thumbnail.url }}" />
                        {% endif %}
                        <a href="{{ tutorial.get_absolute_url }}">{{ tutorial.title }} </a> 
                        {% if tutorial.description %} <p> {{ tutorial.description }} </p> {% endif %}
                    </div>
                </td>
                <td>
                    {% with date=tutorial.pubdate|naturaltime %}
                        {{ date }}
                    {% endwith %}
                </td>
                <td>
                    {{ tutorial.introduction|truncatechars:200|emarkdown }}
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

{% endblock %}

templates/tutorial/by_category.html
{% extends "tutorial/base.html" %}
{% load static %}

{% block title %}
    {{ category.title }}
{% endblock %}

{% block headline %}
    {{ category.title }}
{% endblock %}

{% block breadcrumb %}
    <li class="unavailable"><a href="#">Par catégorie</a></li>
    <li class="current"><a href="#">{{ category.title }}</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <dl class="sub-nav">
            <dt>Catégorie :</dt>

            <dd class="{% ifequal category.slug "tous" %}active{% endifequal %}">
                <a href="{% url "pdp.tutorial.views.by_category" "tous" %}">
                    Tous
                </a>
            </dd>

            {% for c in categories %}
                <dd class="{% ifequal category.slug c.slug %}active{% endifequal %}">
                    <a href="{{ c.get_absolute_url }}">
                        {{ c.title }} ({{ c.get_tutorial_count }})
                    </a>
                </dd>
            {% endfor %}

            <dd class="{% ifequal category.slug "autres" %}active{% endifequal %}">
                <a href="{% url "pdp.tutorial.views.by_category" "autres" %}">
                    Non classés
                </a>
            </dd>
 
            {% if user.is_authenticated %}
                <dd class="{% ifequal category.slug "beta" %}active{% endifequal %}">
                    <a href="{% url "pdp.tutorial.views.by_category" "beta" %}">Bêta</a>
                </dd>
            {% endif %}
        </dl>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        {% if tutorials %}
            <div class="tutorial-items">
                {% for tutorial in tutorials %}
                    {% include "tutorial/tutorial_item.part.html" %}
                {% endfor %}
            </div>
        {% else %}
            <p>Aucun tutoriel disponible dans cette catégorie.</p>
        {% endif %}
    </div>
</div>

{% include "misc/pagination.part.html" %}

{% endblock %}

templates/tutorial/edit_part.html
{% extends "tutorial/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Éditer la partie
{% endblock %}

{% block headline %}
    Éditer la partie
{% endblock %}

{% block headline-sub %}
    {{ part.title }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ part.tutorial.get_absolute_url }}">{{ part.tutorial.title }}</a></li>
    <li><a href="{{ part.get_absolute_url }}">{{ part.title }}</a></li>
    <li class="current"><a href="#">Éditer la partie</a></li>
{% endblock %}

{% block content %}

{% include "tutorial/part_common.part.html" %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% endblock %}

templates/tutorial/edit_tutorial.html
{% extends "tutorial/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Éditer le tutoriel
{% endblock %}

{% block headline %}
    Éditer le tutoriel
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ tutorial.get_absolute_url }}">{{ tutorial.title }}</a></li>
    <li class="current"><a href="#">Éditer le tutoriel</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-6 columns">
        <h2>Général</h2>
        {% crispy form %}
    </div>
    <div class="large-6 columns">
        <h2>Auteurs</h2>

        <form action="{% url "pdp.tutorial.views.modify_tutorial" %}" method="post">
            <div class="row collapse">
                <div class="small-10 columns">
                    <input type="text" name="author" placeholder="Nom de l'utilisateur à ajouter…" />
                </div>
                <div class="small-2 columns">
                    <button type="submit" class="button" name="add_author">
                        Ajouter
                    </button>
                </div>
            </div>
            <input type="hidden" name="tutorial" value="{{ tutorial.pk }}" />
            {% csrf_token %}
        </form>

        <form action="{% url "pdp.tutorial.views.modify_tutorial" %}" method="post">
            <table>
                <thead>
                    <th>Auteur</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    {% for member in tutorial.authors.all %}
                        <tr>
                            <td>{% include "member/member_item_common.part.html" %}</td>
                            <td>
                                {% if tutorial.authors.count > 1 %}
                                <button type="submit" name="author" value="{{ member.pk }}">
                                    Supprimer
                                </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <input type="hidden" name="remove_author" value="1" />
            <input type="hidden" name="tutorial" value="{{ tutorial.pk }}" />
            {% csrf_token %}
        </form>

    </div>
</div>

{% endblock %}

templates/tutorial/feeds.part.html
<a href="#" class="button secondary dropdown {% if request.path != '/' %}large{% endif %}" data-dropdown="tutorials-drop-feeds">
    S’abonner
</a><br />
<ul id="tutorials-drop-feeds" class="f-dropdown">
    <li><a href="{% url "tutorial-feed-rss" %}">Nouveaux tutoriels (RSS)</a></li>
    <li><a href="{% url "tutorial-feed-atom" %}">Nouveaux tutoriels (ATOM)</a></li>
</ul>

templates/tutorial/index.html
{% extends "tutorial/base.html" %}
{% load cache %}

{% block title %}
    Liste des tutoriels
{% endblock %}

{% block meta %}
    <meta name="description" content="Les tutoriels vous permettent d'apprendre sur divers sujets axés autour de la programmation et de l'informatique." />
{% endblock %}

{% block header %}
    <h1>
        Tutoriels
    </h1>
    <p>
        Les tutoriels vous permettent <strong>d'apprendre</strong> sur divers
        sujets axés autour de la programmation et de l'informatique.
        De nombreux auteurs font confiance à Progdupeupl pour partager
        leurs connaissances avec les autres membres.
        <strong>
            Pourquoi pas vous ?
        </strong>
    </p>
    <div class="button-group button-center" style="margin-bottom: 2em;">
        <a href="{% url "pdp.tutorial.views.add_tutorial" %}" class="button success large">
            Rédiger
        </a>
        <a href="{% url "pdp.tutorial.views.import_tutorial" %}" class="button large">
            Importer
        </a>
    </div>
{% endblock %}

{% block headline %}
    Liste des tutoriels
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-8 columns">
        <h2>À la une</h2>
        {% cache 120 tutorials-index %}
            {% if tutorials %}
                <div class="tutorial-items">
                    {% for tutorial in tutorials %}
                        {% include "tutorial/tutorial_item.part.html" %}
                    {% endfor %}
                </div>
            {% else %}
                <p>Aucun tutoriel disponible.</p>
            {% endif %}
        {% endcache %}
    </div>

    <div class="large-4 columns">
        <h2>Catégories</h2>
        <ul>
            <li>
                <a href="{% url "pdp.tutorial.views.by_category" "tous" %}">
                    Tous les tutoriels
                </a>
            </li>
            {% for category in categories %}
                <li>
                    <a href="{{ category.get_absolute_url }}">
                        {{ category }} ({{ category.get_tutorial_count }})
                    </a>
                </li>
            {% endfor %}
            <li>
                <a href="{% url "pdp.tutorial.views.by_category" "autres" %}">
                     Non classés
                 </a>
             </li>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url "pdp.tutorial.views.by_category" "beta" %}">
                        Bêta
                    </a>
                </li>
            {% endif %}
        </ul>

        {% if random_tuto %}
            <h2>Au hasard…</h2>
            {% with tutorial=random_tuto %}
                {% include "tutorial/tutorial_item_small.part.html" %}
            {% endwith %}
        {% endif %}
    </div>
</div>

<div class="row" style="margin-top: 2em; margin-bottom: 2em;">
    <div class="large-12 columns">
        <div class="button-group button-center">
            <a href="{% url "pdp.tutorial.views.by_category" "tous" %}" class="button large">
                Tous les tutoriels
            </a>
            {% include "tutorial/feeds.part.html" %}
        </div>
    </div>
</div>

{# Validation stuff #}

{% if perms.tutorial.change_tutorial %}
<div class="row">
    <div class="large-12 columns">
        <h2>En attente de validation</h2>
        {% cache 120 tutorials-pending %}
        {% if pending_tutorials %}
            <div class="tutorial-items">
                {% for tuto in pending_tutorials %}
                    <div class="row article-publication-item">
                        <div class="small-1 columns">
                            {% with date=tuto.pubdate %}
                                {% include "misc/datebox.part.html" %}
                            {% endwith %}
                        </div>
                        <div class="small-8 columns">
                            <a href="{{ tuto.get_absolute_url }}">{{ tuto.title }}</a>
                            <p>{{ tuto.description }}</p>
                        </div>
                        <div class="small-3 columns">
                            <form action="{% url "pdp.tutorial.views.modify_tutorial" %}" method="post">
                                <div class="button-group even-2 expand">
                                    <button type="submit" class="button success" name="validate">
                                        Valider
                                    </button>
                                    <button type="submit" class="button alert" name="refuse">
                                        Refuser
                                    </button>
                                </div>
                                <input type="hidden" name="tutorial" value="{{ tuto.pk }}">
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>Aucun tutoriel en attente de validation.</p>
        {% endif %}
        {% endcache %}
    </div>
</div>
{% endif %}

{% endblock %}

templates/tutorial/new_chapter.html
{% extends "tutorial/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Nouveau chapitre
{% endblock %}

{% block headline %}
    Nouveau chapitre
{% endblock %}

{% block headline-sub %}
    {{ part.title }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ part.tutorial.get_absolute_url }}">{{ part.tutorial.title }}</a></li>
    {% if part.tutorial.size != "M" %}
        <li><a href="{{ part.get_absolute_url }}">{{ part.title }}</a></li>
    {% endif %}
    <li class="current"><a href="#">Nouveau chapitre</a></li>
{% endblock %}

{% block content %}

{% include "tutorial/chapter_common.part.html" %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% endblock %}

templates/tutorial/part_common.part.html
{# File describing the point of parts #}

<div class="row">
    <div class="large-12 columns">
        <p>
            Les parties permettent, dans le cas de tutoriels conséquents, d'organiser
            les différents chapitres de votre tutoriel en sections. Typiquement, on
            pourra envisager une partie permettant la découvetre de la notion, une
            autre concernant l'approfondissement puis une troisième en tant qu'annexe.
        </p>
    </div>
</div>

templates/tutorial/tutorial_item_small.part.html
{% load static %}

{# TODO: use a custom css class for this kind of elements #}
<div class="row collapse">
    <div class="small-2 column" style="text-align: center;">
        <a href="{{ tutorial.get_absolute_url }}">
            {% if tutorial.thumbnail %}
                <img src="{{ tutorial.thumbnail.url }}" alt="" width="48" />
            {% else %}
                {% if tutorial.is_article %}
                <img src="{% static "img/article/blank.png" %}" alt="" width="48" />
                {% else %}
                <img src="{% static "img/tutorial/blank.png" %}" alt="" width="48" />
                {% endif %}
            {% endif %}
        </a>
    </div>
    <div class="small-10 column" style="padding-left: 5px;">
        <a href="{{ tutorial.get_absolute_url }}">{{ tutorial.title }}</a>
        <p>{{ tutorial.description }}</p>
    </div>
</div>